services:
- type: web
  name: rvn-rust
  runtime: rust
  repo: https://github.com/leothorp/rust-v-node
  plan: free
  region: oregon
  buildCommand: cargo build --release
  startCommand: cargo run --release
  rootDir: rust-app
  envVars:
    - key: ROCKET_ADDRESS
      value: 0.0.0.0
- type: web
  name: rvn-node
  runtime: node
  repo: https://github.com/leothorp/rust-v-node
  plan: free
  region: oregon
  buildCommand: pnpm i
  startCommand: pnpm run start
  rootDir: node-app
